### PR TITLE
Add testing support for Puppet Types

### PR DESCRIPTION
**Pull request by bodepd**
This commit adds support for testing the following
common features of types:

* parameters available
* properties available
* features
* default provider
* that param value(s) are valid

There are still a few things that need to be implemented:
* default parameter values
* autorequires
* munging
* .to_s methods (I am not sure how to test this :) )

### CODE REVIEW

**Comment by DavidS** [comment]
@jeffmccune @haus @bodepd can we get this merged, please?

**Comment by igalic** [comment]
@DavidS well, first of all, it'll need a rebase.

**Comment by DavidS** [comment]
Rebasing was easy enough, but the result is not functional and fails on puppet 3.

Code: https://github.com/DavidS/rspec-puppet/tree/type_support
Travis: https://travis-ci.org/DavidS/rspec-puppet/builds/64303815

**Comment by bodepd** [comment]
that's really strange b/c I definilely developed it against Puppet 3 :) or at least I thought I did.

**Comment by DavidS** [comment]
Looking deeper into the test failures, it starts innocently enough with 3.2 and 3.4 reporting: 

```
  1) fake tests that create a resource instance should pass when providers match
     Failure/Error: should be_valid_type.with_provider(:default)
     Puppet::Error:
       Invalid parameter provider(:provider)
```

Starting with 3.6, something in the initialisation seems to have broken:

```
  1) fake tests of the types parameters checks should fail for 2 baddies
     Failure/Error: expect do
       expected RSpec::Expectations::ExpectationNotMetError with message matching /Invalid parameters: one,two/, got #<NoMethodError: undefined method `validparameter?' for nil:NilClass> with backtrace:
```

This class of errors seems to persist through 4.x

It'd be great, if you could take a closer look at the code. Maybe it's just a little thing.

**Comment by DavidS** [comment]
Yay, I ofund the problem: https://github.com/DavidS/rspec-puppet/commit/6507a175e0cf4a9422c89bdd487d54aa1b4f8796

I'll write up some docs later and merge this.

**Comment by DavidS** [comment]
Merged as #313

**Comment by bodepd** [comment]
@DavidS sorry that I've been a been too distracted to help here. I'm glad that you ultimately found this code to be useful enough to merge!

**Pull request closed without merging**
