### PR TITLE
Monkey Patch windows libraries for when kernel fact is set.

### PR DESCRIPTION
**Pull request by TraGicCode**
When running rspec-puppet on a non-windows node ( in my case a mac ) and set the :kernel windows fact to windows the :ipaddress fact begins to be evaluated for a windows machine ( because it's confined by this fact ) which causes some win32 libraries to get required.

Test to reproduce this
```ruby
require 'spec_helper'

describe 'role::sqlserver' do
    let(:facts) do
      {
        architecture:           'x64',
        osfamily:               'windows',
        kernel:                 'windows',
        operatingsystem:        'windows',
        operatingsystemrelease: '2016',
        staged_package:         nil,
      }
    end

    it { is_expected.to compile.with_all_deps }
end

```

Stack Trace
```
1) role::sqlserver should compile into a catalogue without dependency cycles should compile into a catalogue without dependency cycles
     Failure/Error: it { is_expected.to compile.with_all_deps }

     LoadError:
       cannot load such file -- win32ole
     # ./.bundle/ruby/2.4.0/gems/rspec-puppet-2.6.9/lib/rspec-puppet/monkey_patches.rb:282:in `require'
     # ./.bundle/ruby/2.4.0/gems/rspec-puppet-2.6.9/lib/rspec-puppet/monkey_patches.rb:282:in `require'
     # ./.bundle/ruby/2.4.0/gems/facter-2.5.1/lib/facter/util/wmi.rb:18:in `connect'
     # ./.bundle/ruby/2.4.0/gems/facter-2.5.1/lib/facter/util/wmi.rb:31:in `execquery'
     # ./.bundle/ruby/2.4.0/gems/facter-2.5.1/lib/facter/util/ip/windows.rb:100:in `network_adapter_configurations'
     # ./.bundle/ruby/2.4.0/gems/facter-2.5.1/lib/facter/util/ip/windows.rb:140:in `get_preferred_network_adapters'
     # ./.bundle/ruby/2.4.0/gems/facter-2.5.1/lib/facter/util/ip/windows.rb:115:in `get_preferred_ipv4_adapters'
     # ./.bundle/ruby/2.4.0/gems/facter-2.5.1/lib/facter/ipaddress.rb:110:in `block (2 levels) in <top (required)>'
     # ./.bundle/ruby/2.4.0/gems/facter-2.5.1/lib/facter/util/resolution.rb:157:in `resolve_value'
     # ./.bundle/ruby/2.4.0/gems/facter-2.5.1/lib/facter/core/resolvable.rb:63:in `block (2 levels) in value'
     # ./.bundle/ruby/2.4.0/gems/facter-2.5.1/lib/facter/core/resolvable.rb:62:in `block in value'
     # ./.bundle/ruby/2.4.0/gems/facter-2.5.1/lib/facter/core/resolvable.rb:84:in `with_timing'
     # ./.bundle/ruby/2.4.0/gems/facter-2.5.1/lib/facter/core/resolvable.rb:61:in `value'
     # ./.bundle/ruby/2.4.0/gems/facter-2.5.1/lib/facter/util/fact.rb:161:in `block in find_first_real_value'
     # ./.bundle/ruby/2.4.0/gems/facter-2.5.1/lib/facter/util/fact.rb:160:in `each'
     # ./.bundle/ruby/2.4.0/gems/facter-2.5.1/lib/facter/util/fact.rb:160:in `find_first_real_value'
     # ./.bundle/ruby/2.4.0/gems/facter-2.5.1/lib/facter/util/fact.rb:113:in `block in value'
     # ./.bundle/ruby/2.4.0/gems/facter-2.5.1/lib/facter/util/fact.rb:145:in `searching'
     # ./.bundle/ruby/2.4.0/gems/facter-2.5.1/lib/facter/util/fact.rb:110:in `value'
     # ./.bundle/ruby/2.4.0/gems/facter-2.5.1/lib/facter/util/collection.rb:130:in `value'
     # ./.bundle/ruby/2.4.0/gems/facter-2.5.1/lib/facter.rb:117:in `value'
     # ./.bundle/ruby/2.4.0/gems/puppet-5.3.2/lib/puppet/indirector/catalog/compiler.rb:368:in `block in set_server_facts'
     # ./.bundle/ruby/2.4.0/gems/puppet-5.3.2/lib/puppet/indirector/catalog/compiler.rb:367:in `each'
     # ./.bundle/ruby/2.4.0/gems/puppet-5.3.2/lib/puppet/indirector/catalog/compiler.rb:367:in `set_server_facts'
     # ./.bundle/ruby/2.4.0/gems/puppet-5.3.2/lib/puppet/indirector/catalog/compiler.rb:69:in `block in initialize'
     # ./.bundle/ruby/2.4.0/gems/puppet-5.3.2/lib/puppet/util/profiler/around_profiler.rb:58:in `profile'
     # ./.bundle/ruby/2.4.0/gems/puppet-5.3.2/lib/puppet/util/profiler.rb:51:in `profile'
     # ./.bundle/ruby/2.4.0/gems/puppet-5.3.2/lib/puppet/indirector/catalog/compiler.rb:68:in `initialize'
     # ./.bundle/ruby/2.4.0/gems/puppet-5.3.2/lib/puppet/indirector/indirection.rb:334:in `new'
     # ./.bundle/ruby/2.4.0/gems/puppet-5.3.2/lib/puppet/indirector/indirection.rb:334:in `make_terminus'
     # ./.bundle/ruby/2.4.0/gems/puppet-5.3.2/lib/puppet/indirector/indirection.rb:123:in `terminus'
     # ./.bundle/ruby/2.4.0/gems/puppet-5.3.2/lib/puppet/indirector/indirection.rb:321:in `prepare'
     # ./.bundle/ruby/2.4.0/gems/puppet-5.3.2/lib/puppet/indirector/indirection.rb:185:in `find'
     # ./.bundle/ruby/2.4.0/gems/rspec-puppet-2.6.9/lib/rspec-puppet/adapters.rb:83:in `catalog'
     # ./.bundle/ruby/2.4.0/gems/rspec-puppet-2.6.9/lib/rspec-puppet/adapters.rb:161:in `catalog'
     # ./.bundle/ruby/2.4.0/gems/rspec-puppet-2.6.9/lib/rspec-puppet/support.rb:355:in `build_catalog_without_cache'
     # ./.bundle/ruby/2.4.0/gems/rspec-puppet-2.6.9/lib/rspec-puppet/support.rb:376:in `block in build_catalog'
     # ./.bundle/ruby/2.4.0/gems/rspec-puppet-2.6.9/lib/rspec-puppet/cache.rb:17:in `get'
     # ./.bundle/ruby/2.4.0/gems/rspec-puppet-2.6.9/lib/rspec-puppet/support.rb:375:in `build_catalog'
     # ./.bundle/ruby/2.4.0/gems/rspec-puppet-2.6.9/lib/rspec-puppet/support.rb:75:in `block in load_catalogue'
     # ./.bundle/ruby/2.4.0/gems/rspec-puppet-2.6.9/lib/rspec-puppet/support.rb:319:in `with_vardir'
     # ./.bundle/ruby/2.4.0/gems/rspec-puppet-2.6.9/lib/rspec-puppet/support.rb:69:in `load_catalogue'
     # ./.bundle/ruby/2.4.0/gems/rspec-puppet-2.6.9/lib/rspec-puppet/example/class_example_group.rb:7:in `catalogue'
     # ./.bundle/ruby/2.4.0/gems/rspec-puppet-2.6.9/lib/rspec-puppet/support.rb:10:in `block in subject'
     # ./.bundle/ruby/2.4.0/gems/rspec-puppet-2.6.9/lib/rspec-puppet/matchers/compile.rb:23:in `matches?'
     # ./spec/classes/role/sqlserver_spec.rb:27:in `block (3 levels) in <top (required)>'
```

### CODE REVIEW

**Comment by TraGicCode** [comment]
Faking out the require allowed me to get a little further.  Now it's blowing from the code getting further in facter when loading windows code for the :ipaddress fact.  Now it's trying to require the win32/resolv library.  I'm going to also fake out the require for this too.

**Comment by TraGicCode** [comment]
These changes should now allow people to set the :kernel fact in rspec-puppet to windows without is blowing up on a non-windows machine trying to load windows libraries.  Can anyone on the puppet team verify that i am monkey patching the appropriate way?

**Comment by TraGicCode** [comment]
Looks like it failed unrelated to my change.  Can someone retrigger a build on this?

**Comment by logicminds** [comment]
Any update on this.  Been having this problem for a while now.

**Comment by asedge** [comment]
I have seen this `win32ole` problem before and a coworker of mine has fixed it.  You are on the right track regarding facter and `:ipaddress`.  The solution is to provide facts for `:ipaddress` and possibly also `:macaddress` so facter doesn't try to resolve them automatically.  Better yet, start using [rspec-puppet-facts](https://github.com/mcanevet/rspec-puppet-facts#usage) and loop over your tests using the `on_supported_os` helper.  Those facts, and many others, will be automatically created for you using facterdb, [see here](https://github.com/camptocamp/facterdb/blob/master/facts/3.0/windows-10-x86_64.facts#L26-L36) and will be yielded back to you as part of the loop.  I hope this helps, you might find that this PR is unnecessary.

**Comment by TraGicCode** [comment]
@logicminds @asedge Closing this because when i get master this issue seems to go away.  Another release that should be cut that has not been yet.

**Comment by dandunckelman** [comment]
@TraGicCode what fixed the require of `win32ole`, & `win32/resolv`?  I just updated my project, and I still get failures for those.

Also, even when I add those into the monkey patching, I get autoload failures like this:

```
error during compilation:
  Evaluation Error: Error while evaluating a Resource Statement, Evaluation Error:
    Error while evaluating a Function Call, Could not autoload puppet/type/package:
      Could not autoload puppet/provider/package/windows:
        uninitialized constant Puppet::Util::Windows
          (file: module/spec/fixtures/modules/ta_windows/manifests/expand_file.pp, line: 17, column: 8)
            (file: module/spec/fixtures/modules/ta_windows/manifests/activation.pp, line: 7)
```

```
Evaluation Error: Error while evaluating a Resource Statement,
  Could not autoload puppet/type/registry_key:
    Could not autoload puppet/provider/registry_key/registry:
      uninitialized constant Puppet::Util::Windows
        (file: module/spec/fixtures/modules/ta_windows/manifests/default_browser.pp, line: 21, column: 3)
```

**Pull request closed without merging**
