### PR TITLE
Support Sensitive class params

### PR DESCRIPTION
**Pull request by dividedmind**
This adds a trivial wrapper type and a helper method to class examples.

### CODE REVIEW

**Comment by ghoneycutt** [comment]
+1 for this functionality. Would like to use Sensitive but need the tests to pass first.

**Comment by ghoneycutt** [comment]
BTW, the travis failings seem due to an incorrect matrix of ruby/puppet versions and not to this commit.

**Comment by rodjek** [comment]
Targeting for 2.7.0

**Comment by TraGicCode** [comment]
@rodjek Any updates on this?

@dividedmind Can you also update the documentation on using this?

**Comment by eputnam** [comment]
+1 on getting this into rspec-puppet, any updates?

**Pull request closed without merging**
