### PR TITLE
Fix: site.pp content is not being imported

### PR DESCRIPTION
**Pull request by jk2l**
Patch for the issue mentioned in https://github.com/rodjek/rspec-puppet/issues/322#issuecomment-237459594

### CODE REVIEW

**Comment by rnelson0** [comment]
@jk2l You'll need to add https://github.com/voxpupuli/puppet-community_kickstarts/blob/master/Gemfile#L30 to the Gemfile to fix the remaining errors, I believe.

**Comment by jk2l** [comment]
@rnelson0 patching the Gemfile is not a problem, but i am not sure do the repo owner have their own release guideline for this repo...

**Comment by rnelson0** [comment]
I think it would be acceptable to add that to this PR, as long as it's in a separate commit.

**Comment by jk2l** [comment]
@rnelson0 It seem it still break for 1.8.7 + Puppet 3. Not sure how that part fix

**Comment by rnelson0** [comment]
I have no idea, that makes no sense to me. Perhaps @DavidS may have a suggestion?

**Comment by jk2l** [comment]
oh that seem to be fixed by https://github.com/rodjek/rspec-puppet/pull/394 so just need to wait for that PR pull into master and then do a rebase and merge

**Comment by DavidS** [comment]
I just sorted out the Gemfile, so it works again on all supported platforms. If you could rebase, we could see how the code is faring now.

Thanks for your patience.

**Comment by DavidS** [comment]
Also, wow me, for miscklicking >.<

Apologies for the noise.

**Pull request closed without merging**
