### PR TITLE
Fix: incorrect trusted node data

### PR DESCRIPTION
**Pull request by jk2l**
https://github.com/rodjek/rspec-puppet/issues/400

### CODE REVIEW

**Comment by hlindberg** [comment]
A `push_context` is in itself not bad, but it really needs to be balanced with a `pop_context`, unless naturally there is just setup for a single run that then exits the process.
If it keeps piling on contexts (i.e. never pops), then in it is bad as it will consume memory and gradually make context lookups slower.
I could not determine if the `push_context` in this PR is bad or not - would need to understand a lot more than what I could quickly glean from the source around where it appears.

**Comment by jk2l** [comment]
The code basically copy from https://github.com/puppetlabs/puppet/blob/ed209118fceb6433b51c88c10883cb7415b36adb/lib/puppet/test/test_helper.rb i am not entirely sure how the logic flow internally

**Comment by DavidS** [comment]
I've re-read the code, and this should wrap the `super` call at https://github.com/rodjek/rspec-puppet/blob/master/lib/rspec-puppet/adapters.rb#L148 . That will make it puppet4 only, and allow you to unconditionally use something like 

```
result = nil
Puppet.override({ :trusted_information ... }, "rspec-puppet test scope") do
  result = super
end
result
```

as that code only runs on puppet 4 by design.

**Comment by jk2l** [comment]
So what is the approach of fixing trusted node data support for rspec?

**Comment by DavidS** [comment]
@jk2l it'd be great if you could test out if the approach I described in my earlier comment works for your test case.

**Comment by rodjek** [comment]
Looks like #444 has been merged in which also implements this, so I'll close this PR. Thank you for the contribution though!

**Pull request closed without merging**
