### PR TITLE
Added a Post Condition Hook

### LINKED ISSUE #516: Need a post_condition hook
I've run into cases a couple of times where I needed a `post_condition` in addition to the existing `pre_condition` to do what I need to do.

I get that this is usually indicative of a code-smell, but, when messing about with the guts of Puppet, you may need to order things around what you're testing.

### PR DESCRIPTION
**Pull request by trevor-vaughan**
This adds a 'post_condition' hook that compliments the 'pre_condition'
hook but allows you to place code *after* the current code.

Closes #516

### CODE REVIEW

**Comment by trevor-vaughan** [comment]
@rodjek Any changes needed for this?

**Comment by DavidS** [comment]
The code itself seems to be solid! 

Please add a short description of `post_condition` to the README at https://github.com/rodjek/rspec-puppet/#specifying-extra-code-to-load-pre-conditions.

It also seems that the tests should verify that the file has made its way into the catalog.

**Comment by trevor-vaughan** [comment]
@DavidS Updated the README. I have no idea how to test that the catalog is correct since `pre_condition` wasn't tested in the original test suite. It certainly works in anger :-D.

**Comment by DavidS** [comment]
@trevor-vaughan added the tests at the "right" place. If you concur, we can squash the whole branch down to a single commit for merging.

**Comment by trevor-vaughan** [comment]
@DavidS Works for me. Squash and Merge away (and thanks for adding the tests)!

**Comment by DavidS** [comment]
I had to update it a bit to make it work for puppet 3 and earlier, but now it passes.

**Pull request merged**
