### PR TITLE
DO NOT MERGE (SDK-116) Enable appveyor testing

### PR DESCRIPTION
**Pull request by james-stocks**
Add appveyor config

The test combinations are much less than for .travis.yml due to:

1. We do not want to repeat all testing. Given that travis is green, we only want assurance that nothing Windows-specific is a problem.
2. appveyor is not as flexible as travis. It is not possible to matrix multiple environment variables into test permutations, or to define specific include/excludes from your matrix. You can only define each and every combination of environment variables you want tested.

### CODE REVIEW

**Comment by james-stocks** [comment]
Does not yet reflect the changes to .travis.yml in #482

**Comment by james-stocks** [comment]
DO NOT MERGE - still working on the config

**Comment by james-stocks** [comment]
Test failures on this PR relate to #481  - tests that use posix file paths will fail because the execution on Windows expects a 'fully qualified' path to be a Windows path

**Comment by james-stocks** [comment]
This PR is now blocked on #481 - some of the spec tests are failing on Windows

**Comment by DavidS** [comment]
The blocking issue was closed through #498. Can we get this rebased/going again?

**Comment by james-stocks** [comment]
This was superseded by https://github.com/rodjek/rspec-puppet/pull/520 - forgot to close this one, sorry.

**Comment by DavidS** [comment]
So much the better :-D

**Pull request closed without merging**
