### PR TITLE
Merge node derived facts only if the node name has been specified

### PR DESCRIPTION
**Pull request by rodjek**
Re #549 

@trevor-vaughan, @rnelson0, @ekohl - I believe this should solve your issue, so if you could run it against your affected modules and let me know, that'd be great.

### CODE REVIEW

**Comment by rnelson0** [comment]
I can confirm that this works for my code (a controlrepo, not a component module).

**Comment by rodjek** [comment]
Thanks @rnelson0! I'll wait for the others to respond before merging this in, but in the meantime I'll work up some tests so that we don't see this regression in the future.

**Comment by rodjek** [comment]
@trevor-vaughan confirmed this fixes the issue(s) he was seeing in #549 as well.

**Comment by alexjfisher** [comment]
Fixes test failures seen in https://github.com/voxpupuli/puppet-rundeck/pull/322

**Comment by mmoll** [comment]
Fixes the problems we're seeing at @theforeman modules 👍

**Comment by rodjek** [comment]
Thanks all, 2.6.3 has just been pushed to rubygems

**Pull request merged**
