### PR TITLE
Implement RSpec::Puppet::Coverage.add_filter_regex

### LINKED ISSUE #158: [Coverage] Exclude certain resources from coverage report
Would be cool to exclude certain resources ( like anchor's ) from the coverage reports as sometimes these can't be tested.

### PR DESCRIPTION
**Pull request by scotje**
Closes #158

### CODE REVIEW

**Comment by scotje** [comment]
Only CI failure is due to the old Ruby 1.8-compatible version of rspec not having the `output` matcher.

**Review by DavidS — APPROVED** [review]
Added initial shot at docs (please verify!) and added some more handling of edge-cases when processing regex-anchors in filters.

**Comment by DavidS** [comment]
Damnit - ruby 1.8.7 is not supporting `(?>!...)` negative lookbehinds. how about we just drop support for that ruby version?

**Comment by scotje** [comment]
> Damnit - ruby 1.8.7 is not supporting `(?>!...)` negative lookbehinds. how about we just drop support for that ruby version?

Yeah I'm not worried about Ruby 1.8.7 failures, and I'd be OK with updating the gemspec to require at least Ruby 2.1 for the 2.8.0 release.

**Pull request merged**
