### PR TITLE
More Stubbed Windows Gems

### LINKED ISSUE #599: Cannot load such file -- win32/registry
# Summary
When running Bash on Linux, testing a Windows-specific manifest fails w/ this error:

```
Failures:

  1) ta_base::windows on windows-2012 R2-x64 should contain Class[chocolatey] with choco_install_location => "C:/ProgramData/chocolatey"
     Failure/Error:
       it { should contain_class("chocolatey")
         .with(
           "choco_install_location" => "C:/ProgramData/chocolatey",
         )
       }

     LoadError:
       cannot load such file -- win32/registry
     # /home/dunk/.rvm/gems/ruby-2.3.1@puppet-testing/gems/rspec-puppet-2.6.8/lib/rspec-puppet/monkey_patches.rb:275:in `require'
     # /home/dunk/.rvm/gems/ruby-2.3.1@puppet-testing/gems/rspec-puppet-2.6.8/lib/rspec-puppet/monkey_patches.rb:275:in `require'
     # /home/dunk/.rvm/gems/ruby-2.3.1@puppet-testing/gems/facter-2.4.6/lib/facter/util/registry.rb:4:in `hklm_read'
     # /home/dunk/.rvm/gems/ruby-2.3.1@puppet-testing/gems/facter-2.4.6/lib/facter/domain.rb:80:in `block (2 levels) in <top (required)>'
     # /home/dunk/.rvm/gems/ruby-2.3.1@puppet-testing/gems/facter-2.4.6/lib/facter/util/resolution.rb:157:in `resolve_value'
     # /home/dunk/.rvm/gems/ruby-2.3.1@puppet-testing/gems/facter-2.4.6/lib/facter/core/resolvable.rb:63:in `block (2 levels) in value'
     # /home/dunk/.rvm/gems/ruby-2.3.1@puppet-testing/gems/facter-2.4.6/lib/facter/core/resolvable.rb:62:in `block in value'
     # /home/dunk/.rvm/gems/ruby-2.3.1@puppet-testing/gems/facter-2.4.6/lib/facter/core/resolvable.rb:84:in `with_timing'
     # /home/dunk/.rvm/gems/ruby-2.3.1@puppet-testing/gems/facter-2.4.6/lib/facter/core/resolvable.rb:61:in `value'
     # /home/dunk/.rvm/gems/ruby-2.3.1@puppet-testing/gems/facter-2.4.6/lib/facter/util/fact.rb:161:in `block in find_first_real_value'
     # /home/dunk/.rvm/gems/ruby-2.3.1@puppet-testing/gems/facter-2.4.6/lib/facter/util/fact.rb:160:in `each'
     # /home/dunk/.rvm/gems/ruby-2.3.1@puppet-testing/gems/facter-2.4.6/lib/facter/util/fact.rb:160:in `find_first_real_value'
     # /home/dunk/.rvm/gems/ruby-2.3.1@puppet-testing/gems/facter-2.4.6/lib/facter/util/fact.rb:113:in `block in value'
     # /home/dunk/.rvm/gems/ruby-2.3.1@puppet-testing/gems/facter-2.4.6/lib/facter/util/fact.rb:145:in `searching'
     # /home/dunk/.rvm/gems/ruby-2.3.1@puppet-testing/gems/facter-2.4.6/lib/facter/util/fact.rb:110:in `value'
     # /home/dunk/.rvm/gems/ruby-2.3.1@puppet-testing/gems/facter-2.4.6/lib/facter/util/collection.rb:130:in `value'
     # /home/dunk/.rvm/gems/ruby-2.3.1@puppet-testing/gems/facter-2.4.6/lib/facter.rb:117:in `value'
     # /home/dunk/.rvm/gems/ruby-2.3.1@puppet-testing/gems/puppet-4.7.0/lib/puppet/settings.rb:77:in `domain_fact'
     # /home/dunk/.rvm/gems/ruby-2.3.1@puppet-testing/gems/puppet-4.7.0/lib/puppet/defaults.rb:1433:in `block in <module:Puppet>'
     # /home/dunk/.rvm/gems/ruby-2.3.1@puppet-testing/gems/puppet-4.7.0/lib/puppet/settings/base_setting.rb:100:in `default'
     # /home/dunk/.rvm/gems/ruby-2.3.1@puppet-testing/gems/puppet-4.7.0/lib/puppet/settings.rb:1266:in `lookup'
     # /home/dunk/.rvm/gems/ruby-2.3.1@puppet-testing/gems/puppet-4.7.0/lib/puppet/settings.rb:1281:in `interpolate'
     # /home/dunk/.rvm/gems/ruby-2.3.1@puppet-testing/gems/puppet-4.7.0/lib/puppet/settings.rb:1065:in `value'
     # /home/dunk/.rvm/gems/ruby-2.3.1@puppet-testing/gems/puppet-4.7.0/lib/puppet/node/environment.rb:228:in `[]'
     # /home/dunk/.rvm/gems/ruby-2.3.1@puppet-testing/gems/puppet-4.7.0/lib/puppet/parser/compiler.rb:865:in `block in create_settings_scope'
     # /home/dunk/.rvm/gems/ruby-2.3.1@puppet-testing/gems/puppet-4.7.0/lib/puppet/parser/compiler.rb:863:in `create_settings_scope'
     # /home/dunk/.rvm/gems/ruby-2.3.1@puppet-testing/gems/puppet-4.7.0/lib/puppet/parser/compiler.rb:168:in `block (2 levels) in compile'
     # /home/dunk/.rvm/gems/ruby-2.3.1@puppet-testing/gems/puppet-4.7.0/lib/puppet/util/profiler/around_profiler.rb:58:in `profile'
     # /home/dunk/.rvm/gems/ruby-2.3.1@puppet-testing/gems/puppet-4.7.0/lib/puppet/util/profiler.rb:51:in `profile'
     # /home/dunk/.rvm/gems/ruby-2.3.1@puppet-testing/gems/puppet-4.7.0/lib/puppet/parser/compiler.rb:168:in `block in compile'
     # /home/dunk/.rvm/gems/ruby-2.3.1@puppet-testing/gems/puppet-4.7.0/lib/puppet/context.rb:65:in `override'
     # /home/dunk/.rvm/gems/ruby-2.3.1@puppet-testing/gems/puppet-4.7.0/lib/puppet.rb:241:in `override'
     # /home/dunk/.rvm/gems/ruby-2.3.1@puppet-testing/gems/puppet-4.7.0/lib/puppet/parser/compiler.rb:162:in `compile'
     # /home/dunk/.rvm/gems/ruby-2.3.1@puppet-testing/gems/puppet-4.7.0/lib/puppet/parser/compiler.rb:33:in `compile'
     # /home/dunk/.rvm/gems/ruby-2.3.1@puppet-testing/gems/puppet-4.7.0/lib/puppet/indirector/catalog/compiler.rb:266:in `block (2 levels) in compile'
     # /home/dunk/.rvm/gems/ruby-2.3.1@puppet-testing/gems/puppet-4.7.0/lib/puppet/util/profiler/around_profiler.rb:58:in `profile'
     # /home/dunk/.rvm/gems/ruby-2.3.1@puppet-testing/gems/puppet-4.7.0/lib/puppet/util/profiler.rb:51:in `profile'
     # /home/dunk/.rvm/gems/ruby-2.3.1@puppet-testing/gems/puppet-4.7.0/lib/puppet/indirector/catalog/compiler.rb:264:in `block in compile'
     # /home/dunk/.rvm/gems/ruby-2.3.1@puppet-testing/gems/puppet-4.7.0/lib/puppet/util.rb:223:in `block in benchmark'
     # /home/dunk/.rvm/gems/ruby-2.3.1@puppet-testing/gems/puppet-4.7.0/lib/puppet/util.rb:222:in `benchmark'
     # /home/dunk/.rvm/gems/ruby-2.3.1@puppet-testing/gems/puppet-4.7.0/lib/puppet/indirector/catalog/compiler.rb:262:in `compile'
     # /home/dunk/.rvm/gems/ruby-2.3.1@puppet-testing/gems/puppet-4.7.0/lib/puppet/indirector/catalog/compiler.rb:53:in `find'
     # /home/dunk/.rvm/gems/ruby-2.3.1@puppet-testing/gems/puppet-4.7.0/lib/puppet/indirector/indirection.rb:194:in `find'
     # /home/dunk/.rvm/gems/ruby-2.3.1@puppet-testing/gems/rspec-puppet-2.6.8/lib/rspec-puppet/adapters.rb:83:in `catalog'
     # /home/dunk/.rvm/gems/ruby-2.3.1@puppet-testing/gems/rspec-puppet-2.6.8/lib/rspec-puppet/adapters.rb:161:in `catalog'
     # /home/dunk/.rvm/gems/ruby-2.3.1@puppet-testing/gems/rspec-puppet-2.6.8/lib/rspec-puppet/support.rb:354:in `build_catalog_without_cache'
     # /home/dunk/.rvm/gems/ruby-2.3.1@puppet-testing/gems/rspec-puppet-2.6.8/lib/rspec-puppet/support.rb:375:in `block in build_catalog'
     # /home/dunk/.rvm/gems/ruby-2.3.1@puppet-testing/gems/rspec-puppet-2.6.8/lib/rspec-puppet/cache.rb:17:in `get'
     # /home/dunk/.rvm/gems/ruby-2.3.1@puppet-testing/gems/rspec-puppet-2.6.8/lib/rspec-puppet/support.rb:374:in `build_catalog'
     # /home/dunk/.rvm/gems/ruby-2.3.1@puppet-testing/gems/rspec-puppet-2.6.8/lib/rspec-puppet/support.rb:75:in `block in load_catalogue'
     # /home/dunk/.rvm/gems/ruby-2.3.1@puppet-testing/gems/rspec-puppet-2.6.8/lib/rspec-puppet/support.rb:319:in `with_vardir'
     # /home/dunk/.rvm/gems/ruby-2.3.1@puppet-testing/gems/rspec-puppet-2.6.8/lib/rspec-puppet/support.rb:69:in `load_catalogue'
     # /home/dunk/.rvm/gems/ruby-2.3.1@puppet-testing/gems/rspec-puppet-2.6.8/lib/rspec-puppet/example/class_example_group.rb:7:in `catalogue'
     # /home/dunk/.rvm/gems/ruby-2.3.1@puppet-testing/gems/rspec-puppet-2.6.8/lib/rspec-puppet/support.rb:10:in `block in subject'
     # /home/dunk/.rvm/gems/ruby-2.3.1@puppet-testing/gems/rspec-puppet-2.6.8/lib/rspec-puppet/matchers/create_generic.rb:84:in `matches?'
     # ./spec/classes/windows_spec.rb:29:in `block (4 levels) in <top (required)>'

Finished in 0.1754 seconds (files took 4.28 seconds to load)
1 example, 1 failure

Failed examples:

rspec ./spec/classes/windows_spec.rb:29 # ta_base::windows on windows-2012 R2-x64 should contain Class[chocolatey] with choco_install_location => "C:/ProgramData/chocolatey"

/home/dunk/.rvm/rubies/ruby-2.3.1/bin/ruby -I/home/dunk/.rvm/gems/ruby-2.3.1@puppet-testing/gems/rspec-core-3.6.0/lib:/home/dunk/.rvm/gems/ruby-2.3.1@puppet-testing/gems/rspec-support-3.6.0/lib /home/dunk/.rvm/gems/ruby-2.3.1@puppet-testing/gems/rspec-core-3.6.0/exe/rspec 
 spec/classes/windows_spec.rb --color failed
```

## Manifest
```
class ta_base::windows(
  Stdlib::Compat::Absolute_path $choco_install_location = undef,
) {
  class { 'chocolatey':
    choco_install_location => $choco_install_location,
  }

  Package { provider => chocolatey, }

  include ta_windows::wsus_client
}
```

## Spec
```
require "spec_helper"

describe "ta_base::windows" do
  test_on = {
    :supported_os => [
      {
        'operatingsystem'        => 'windows',
        'operatingsystemrelease' => ['2012 R2'],
      }
    ]
  }

  on_supported_os(test_on).each do |os, facts|
    context "on #{os}" do
      let(:facts) do
        facts.merge(chocolateyversion: "0.9.8.33")
      end

      it { is_expected.to compile.with_all_deps }

      it { should contain_class("chocolatey")
        .with(
          "choco_install_location" => "C:/ProgramData/chocolatey",
        )
      }

      it { should contain_class("ta_windows::wsus_client") }
    end
  end
end
```

## Environment
```
Bundler   1.14.6
Rubygems  2.5.1
Ruby      2.3.1p112 (2016-04-26 revision 54768) [x86_64-linux]
GEM_HOME  /home/dunk/.rvm/gems/ruby-2.3.1@puppet-testing
GEM_PATH  /home/dunk/.rvm/gems/ruby-2.3.1@puppet-testing:/home/dunk/.rvm/gems/ruby-2.3.1@global
RVM       1.29.1 (latest)
Git       1.9.1
Platform  x86_64-linux
rubygems-bundler (1.4.4)
```

### Gemfile
```ruby
source "https://rubygems.org"

gem 'puppet', '4.7.0'

group :test do
  gem 'puppet-lint', '2.3.0'
  gem 'puppetlabs_spec_helper', '2.2.0'
  gem 'rspec-puppet', '2.6.8'
  gem 'parallel_tests', '2.14.2'
  gem 'rspec-puppet-facts', '1.8.0', :require => false
  gem 'metadata-json-lint', '2.0.2'
  gem 'semantic_puppet', '1.0.1' # this gem is needed (for metadata-json-lint) until we move to Puppet 4.9.x
end

group :development, :test do
  gem 'beaker-rspec', '6.1.0', :require => false
  gem 'pry', '0.10.4'
end
```

### Gemfile.lock
```
GEM
  remote: https://rubygems.org/
  specs:
    CFPropertyList (2.3.5)
    addressable (2.5.1)
      public_suffix (~> 2.0, >= 2.0.2)
    aws-sdk-v1 (1.67.0)
      json (~> 1.4)
      nokogiri (~> 1)
    beaker (3.20.0)
      aws-sdk-v1 (~> 1.57)
      beaker-hiera (~> 0.0)
      beaker-hostgenerator
      beaker-puppet (~> 0.0)
      beaker-vmpooler (~> 0.1)
      docker-api
      fission (~> 0.4)
      fog (~> 1.38)
      google-api-client (~> 0.9)
      hocon (~> 1.0)
      in-parallel (~> 0.1)
      inifile (~> 3.0)
      in-parallel (~> 0.1)
      inifile (~> 3.0)
      minitar (~> 0.5.4)
      minitest (~> 5.4)
      net-scp (~> 1.2)
      net-ssh (~> 4.0)
      open_uri_redirections (~> 0.2.1)
      rsync (~> 1.0.9)
      stringify-hash (~> 0.0)
      thor (~> 0.19)
      unf (~> 0.1)
    beaker-hiera (0.1.1)
      stringify-hash (~> 0.0.0)
    beaker-hostgenerator (0.10.1)
      deep_merge (~> 1.0)
      stringify-hash (~> 0.0.0)
    beaker-puppet (0.3.0)
      in-parallel (~> 0.1)
      stringify-hash (~> 0.0.0)
    beaker-rspec (6.1.0)
      beaker (~> 3.0)
      rspec (~> 3.0)
      serverspec (~> 2)
      specinfra (~> 2)
    beaker-vmpooler (0.1.0)
      rbvmomi (~> 1.9)
      stringify-hash (~> 0.0.0)
    builder (3.2.3)
    coderay (1.1.1)
    declarative (0.0.9)
    declarative-option (0.1.0)
    deep_merge (1.1.1)
    diff-lcs (1.3)
    docker-api (1.33.6)
      excon (>= 0.38.0)
      json
    excon (0.57.1)
    facter (2.4.6)
    facterdb (0.3.11)
      facter
      jgrep
    faraday (0.12.1)
      multipart-post (>= 1.2, < 3)
    fast_gettext (1.1.0)
    fission (0.5.0)
      CFPropertyList (~> 2.2)
    fog (1.40.0)
      fog-aliyun (>= 0.1.0)
      fog-atmos
      fog-aws (>= 0.6.0)
      fog-brightbox (~> 0.4)
      fog-cloudatcost (~> 0.1.0)
      fog-core (~> 1.43)
      fog-digitalocean (>= 0.3.0)
      fog-dnsimple (~> 1.0)
      fog-dynect (~> 0.0.2)
      fog-ecloud (~> 0.1)
      fog-google (<= 0.1.0)
      fog-json
      fog-local
      fog-openstack
      fog-powerdns (>= 0.1.1)
      fog-profitbricks
      fog-rackspace
      fog-radosgw (>= 0.0.2)
      fog-riakcs
      fog-sakuracloud (>= 0.0.4)
      fog-serverlove
      fog-softlayer
      fog-storm_on_demand
      fog-terremark
      fog-vmfusion
      fog-voxel
      fog-vsphere (>= 0.4.0)
      fog-xenserver
      fog-xml (~> 0.1.1)
      ipaddress (~> 0.5)
      json (>= 1.8, < 2.0)
    fog-aliyun (0.1.0)
      fog-core (~> 1.27)
      fog-json (~> 1.0)
      ipaddress (~> 0.8)
      xml-simple (~> 1.1)
    fog-atmos (0.1.0)
      fog-core
      fog-xml
    fog-aws (1.4.0)
      fog-core (~> 1.38)
      fog-json (~> 1.0)
      fog-xml (~> 0.1)
      ipaddress (~> 0.8)
    fog-brightbox (0.11.0)
      fog-core (~> 1.22)
      fog-json
      inflecto (~> 0.0.2)
    fog-cloudatcost (0.1.2)
      fog-core (~> 1.36)
      fog-json (~> 1.0)
      fog-xml (~> 0.1)
      ipaddress (~> 0.8)
    fog-core (1.44.3)
      builder
      excon (~> 0.49)
      formatador (~> 0.2)
    fog-digitalocean (0.3.0)
      fog-core (~> 1.42)
      fog-json (>= 1.0)
      fog-xml (>= 0.1)
      ipaddress (>= 0.5)
    fog-dnsimple (1.0.0)
      fog-core (~> 1.38)
      fog-json (~> 1.0)
    fog-dynect (0.0.3)
      fog-core
      fog-json
      fog-xml
    fog-ecloud (0.3.0)
      fog-core
      fog-xml
    fog-google (0.1.0)
      fog-core
      fog-json
      fog-xml
    fog-json (1.0.2)
      fog-core (~> 1.0)
      multi_json (~> 1.10)
    fog-local (0.3.1)
      fog-core (~> 1.27)
    fog-openstack (0.1.21)
      fog-core (>= 1.40)
      fog-json (>= 1.0)
      ipaddress (>= 0.8)
    fog-powerdns (0.1.1)
      fog-core (~> 1.27)
      fog-json (~> 1.0)
      fog-xml (~> 0.1)
    fog-profitbricks (3.0.0)
      fog-core (~> 1.42)
      fog-json (~> 1.0)
    fog-rackspace (0.1.5)
      fog-core (>= 1.35)
      fog-json (>= 1.0)
      fog-xml (>= 0.1)
      ipaddress (>= 0.8)
    fog-radosgw (0.0.5)
      fog-core (>= 1.21.0)
      fog-json
      fog-xml (>= 0.0.1)
    fog-riakcs (0.1.0)
      fog-core
      fog-json
      fog-xml
    fog-sakuracloud (1.7.5)
      fog-core
      fog-json
    fog-serverlove (0.1.2)
      fog-core
      fog-json
    fog-softlayer (1.1.4)
      fog-core
      fog-json
    fog-storm_on_demand (0.1.1)
      fog-core
      fog-json
    fog-terremark (0.1.0)
      fog-core
      fog-xml
    fog-vmfusion (0.1.0)
      fission
      fog-core
    fog-voxel (0.1.0)
      fog-core
      fog-xml
    fog-vsphere (1.11.2)
      fog-core
      rbvmomi (~> 1.9)
    fog-xenserver (0.3.0)
      fog-core
      fog-xml
    fog-xml (0.1.3)
      fog-core
      nokogiri (>= 1.5.11, < 2.0.0)
    formatador (0.2.5)
    gettext (3.2.4)
      locale (>= 2.0.5)
      text (>= 1.3.0)
    gettext-setup (0.26)
      fast_gettext (~> 1.1.0)
      gettext (>= 3.0.2)
      locale
    google-api-client (0.13.1)
      addressable (~> 2.5, >= 2.5.1)
      googleauth (~> 0.5)
      httpclient (>= 2.8.1, < 3.0)
      mime-types (~> 3.0)
      representable (~> 3.0)
      retriable (>= 2.0, < 4.0)
    googleauth (0.5.1)
      faraday (~> 0.9)
      jwt (~> 1.4)
      logging (~> 2.0)
      memoist (~> 0.12)
      multi_json (~> 1.11)
      os (~> 0.9)
      signet (~> 0.7)
    hiera (3.4.0)
    hocon (1.2.5)
    httpclient (2.8.3)
    in-parallel (0.1.17)
    inflecto (0.0.2)
    inifile (3.0.0)
    ipaddress (0.8.3)
    jgrep (1.4.1)
      json
    json (1.8.6)
    json-schema (2.8.0)
      addressable (>= 2.4)
    json_pure (1.8.6)
    jwt (1.5.6)
    little-plugger (1.1.4)
    locale (2.1.2)
    logging (2.2.2)
      little-plugger (~> 1.1)
      multi_json (~> 1.10)
    mcollective-client (2.11.0)
      json
      stomp
      systemu
    memoist (0.16.0)
    metaclass (0.0.4)
    metadata-json-lint (2.0.2)
      json-schema (~> 2.8)
      spdx-licenses (~> 1.0)
    method_source (0.8.2)
    mime-types (3.1)
      mime-types-data (~> 3.2015)
    mime-types-data (3.2016.0521)
    mini_portile2 (2.2.0)
    minitar (0.5.4)
    minitest (5.10.2)
    mocha (1.2.1)
      metaclass (~> 0.0.1)
    multi_json (1.12.1)
    multipart-post (2.0.0)
    net-scp (1.2.1)
      net-ssh (>= 2.6.5)
    net-ssh (4.1.0)
    net-telnet (0.1.1)
    nokogiri (1.8.0)
      mini_portile2 (~> 2.2.0)
    open_uri_redirections (0.2.1)
    os (0.9.6)
    parallel (1.11.2)
    parallel_tests (2.14.2)
      parallel
    pry (0.10.4)
      coderay (~> 1.1.0)
      method_source (~> 0.8.1)
      slop (~> 3.4)
    public_suffix (2.0.5)
    puppet (4.7.0)
      facter (> 2.0, < 4)
      hiera (>= 2.0, < 4)
      json_pure (~> 1.8)
    puppet-lint (2.3.0)
    puppet-syntax (2.4.1)
      rake
    puppetlabs_spec_helper (2.2.0)
      mocha (~> 1.0)
      puppet-lint (~> 2.0)
      puppet-syntax (~> 2.0)
      rspec-puppet (~> 2.0)
    rake (12.0.0)
    rbvmomi (1.11.3)
      builder (~> 3.0)
      json (>= 1.8)
      nokogiri (~> 1.5)
      trollop (~> 2.1)
    representable (3.0.4)
      declarative (< 0.1.0)
      declarative-option (< 0.2.0)
      uber (< 0.2.0)
    retriable (3.0.2)
    rspec (3.6.0)
      rspec-core (~> 3.6.0)
      rspec-expectations (~> 3.6.0)
      rspec-mocks (~> 3.6.0)
    rspec-core (3.6.0)
      rspec-support (~> 3.6.0)
    rspec-expectations (3.6.0)
      diff-lcs (>= 1.2.0, < 2.0)
      rspec-support (~> 3.6.0)
    rspec-its (1.2.0)
      rspec-core (>= 3.0.0)
      rspec-expectations (>= 3.0.0)
    rspec-mocks (3.6.0)
      diff-lcs (>= 1.2.0, < 2.0)
      rspec-support (~> 3.6.0)
    rspec-puppet (2.6.8)
      rspec
    rspec-puppet-facts (1.8.0)
      facter
      facterdb (>= 0.3.0)
      json
      mcollective-client
      puppet
    rspec-support (3.6.0)
    rsync (1.0.9)
    semantic_puppet (1.0.1)
      gettext-setup (>= 0.3)
    serverspec (2.39.1)
      multi_json
      rspec (~> 3.0)
      rspec-its
      specinfra (~> 2.68)
    sfl (2.3)
    signet (0.7.3)
      addressable (~> 2.3)
      faraday (~> 0.9)
      jwt (~> 1.5)
      multi_json (~> 1.10)
    slop (3.6.0)
    spdx-licenses (1.1.0)
    specinfra (2.69.0)
      net-scp
      net-ssh (>= 2.7, < 5.0)
      net-telnet
      sfl
    stomp (1.4.4)
    stringify-hash (0.0.2)
    systemu (2.6.5)
    text (1.3.1)
    thor (0.19.4)
    trollop (2.1.2)
    uber (0.1.0)
    unf (0.1.4)
      unf_ext
    unf_ext (0.0.7.4)
    xml-simple (1.1.5)

PLATFORMS
  ruby

DEPENDENCIES
  beaker-rspec (= 6.1.0)
  metadata-json-lint (= 2.0.2)
  parallel_tests (= 2.14.2)
  pry (= 0.10.4)
  puppet (= 4.7.0)
  puppet-lint (= 2.3.0)
  puppetlabs_spec_helper (= 2.2.0)
  rspec-puppet (= 2.6.8)
  rspec-puppet-facts (= 1.8.0)
  semantic_puppet (= 1.0.1)

BUNDLED WITH
   1.14.6
```

Please let me know if any more info is needed.

### PR DESCRIPTION
**Pull request by TraGicCode**
@rodjek Can you verify i'm doing this correct?  Also i couldn't find a way to write a unit test and create a spy for old_require()

Also this produces more errors But will get me and others further when compiling manifests on non-windows nodes.

closes #599

### CODE REVIEW

**Comment by TraGicCode** [comment]
Here are the new errors after this fix.
screen shot 2017-09-21 at 2 14 46 pm

**Comment by dandunckelman** [comment]
@TraGicCode thanks for getting this started.  I just tried using your branch and got this error:

```
Failure/Error: it { should compile }
  error during compilation:
    Evaluation Error:  Error while evaluating a Resource Statement, Evaluation Error:
      Error while evaluating a Function Call, Could not autoload puppet/type/package:
        Could not autoload puppet/provider/package/windows:
          uninitialized constant Puppet::Util::Windows at /mnt/c/Users/dldun/work/ta/scripts/puppet-module-ta_windows/spec/fixtures/modules/ta_windows/manifests/expand_file.pp:18:8 at /mnt/c/Users/dldun/work/ta/scripts/puppet-module-ta_windows/spec/fixtures/modules/ta_windows/manifests/activation.pp:7 on node
```

which threw up on this `package` resource:

```
if ! defined(Package['7zip']) {
  package { '7zip':
    ensure   => installed,
    provider => chocolatey,
  }
}
```

**Comment by TraGicCode** [comment]
Hey dan, I talked to rodjek and based on my conversation I don't think my attempt is actually the right way to solve this problem.  It's actually a very hard problem to solve.  Rodjek is at puppetconf but maybe when he gets back we can figure out what needs to happen.  I really wonder how chef is doing this

**Comment by dandunckelman** [comment]
@TraGicCode thanks for the heads up!

**Comment by TraGicCode** [comment]
I was wondering how chef does this with chefspec..looks like they don't

https://github.com/chefspec/chefspec/issues/405

This is more of an issue with windows and no clean way around this.  @rodjek mentioned lazy-loading requires in the modules that are blowing up could resolve this.  Just a bit of a solution that doesn't quite feel right but you really don't have much of a choice.

**Comment by DavidS** [comment]
Yeah, the options are "run unit-tests on the target system", or "deal with
the scaffolding/monkey-patching fallout". Seeing as we want to enable a
"native" development experience, we'll have to deal with the latter.

**Comment by TraGicCode** [comment]
@DavidS Would you say the approach i was taking is acceptable in regards to monkey-patching?

**Comment by DavidS** [comment]
Looking at https://tickets.puppetlabs.com/browse/PDK-500 and the connected tickets, I believe there is a deeper underlying issue that causes running windows and non-windows tests in the same process cross-contaminating their runtime environment. That is, it seems to be possible to run only windows tests, and only linux tests on the same machine, but not in the same process.

**Comment by DavidS** [comment]
Looking at https://tickets.puppetlabs.com/browse/PDK-500 and the connected tickets, I believe there is a deeper underlying issue that causes running windows and non-windows tests in the same process cross-contaminating their runtime environment. That is, it seems to be possible to run only windows tests, and only linux tests on the same machine, but not in the same process.

**Comment by LTangaF** [comment]
Actually, I wish I understood more why providers are needed at all for spec testing. Providers are used for applying the catalog, not making sure the catalog looks the way we want. There are even methods monkey-patched onto Puppet::Type called suppress_providers and unsupress_providers, but nothing actually uses the flag to change behavior.

**Comment by TraGicCode** [comment]
Deleted my fork and forgot this was out there.  Closing this and conversations should move to #633

**Pull request closed without merging**
